export const lifeLessons = [
  `Every great adventure teaches us something important. In this story, the characters discovered that being brave doesn't mean you're never scared — it means you keep going even when your heart is racing. True courage shows up in small moments, like standing up for a friend, trying something new, or speaking up when something isn't right. The hero of this story learned that asking for help isn't a weakness; it's one of the bravest things you can do. When we face challenges together, we grow stronger and wiser. Remember, you don't have to be perfect to be brave — you just have to keep trying, even when things get tough. That's what makes a truly brave heart!`,

  `This story reminds us that kindness has a special kind of magic. When the characters chose to help others, even when it wasn't easy, they discovered that kindness creates ripples — like throwing a pebble into a pond. One small act of goodness can spread far beyond what we can see. The story also shows us that everyone has struggles we might not know about, and a little understanding goes a long way. Being kind doesn't cost anything, but it means everything to someone who needs it. The greatest adventurers in history weren't just strong — they were compassionate. So carry this lesson with you: treat others the way you wish to be treated, and watch the world become a little brighter because of you.`,

  `What a journey this has been! This story teaches us that mistakes are actually hidden treasures. Every time the characters stumbled, they learned something new that helped them later. Nobody gets everything right the first time — not even the wisest wizards or the strongest heroes! What matters is that we learn from our missteps and try again with more knowledge than before. The character in this story showed us that persistence is a superpower. When you fall down seven times, stand up eight. Each mistake is just a stepping stone on the path to success. So the next time something doesn't go as planned, remember this story and know that you're actually one step closer to getting it right.`,

  `In this story, we learned that friendship is one of the most powerful forces in the world. The characters accomplished things together that they could never have done alone. A true friend is someone who celebrates your victories, supports you through failures, and never stops believing in you — even when you stop believing in yourself. The adventure showed us that different people bring different strengths, and when we combine them, amazing things happen. Listening to each other, sharing our ideas, and working as a team makes every challenge smaller and every victory sweeter. Treasure your friends, be a good friend in return, and remember that together, you can face any adventure that comes your way.`,

  `This story carries a beautiful lesson about honesty and trust. The characters discovered that telling the truth, even when it's difficult, builds something precious — trust. When people know they can rely on your words, doors open and friendships deepen. Lying might seem like an easy way out sometimes, but it always makes things more complicated in the end. The hero of our story chose honesty, and though it wasn't always easy, it led to real respect and genuine connections with others. Being truthful doesn't just help others trust you — it helps you trust yourself. When you live honestly, you never have to worry about keeping stories straight. That freedom is truly powerful.`,

  `What an incredible adventure! This story teaches us that curiosity is the beginning of all great discoveries. The characters asked questions, explored new places, and never stopped wondering "what if?" That spirit of curiosity led them to amazing experiences and knowledge they never expected. Too often, people are afraid to ask questions because they worry about looking silly — but the smartest people in the world are the ones who ask the most questions! Every expert was once a beginner who wasn't afraid to be curious. So keep asking, keep exploring, and keep wondering. The world is full of mysteries waiting for someone just like you to uncover them.`,
];

export function getRandomLesson(): string {
  return lifeLessons[Math.floor(Math.random() * lifeLessons.length)];
}
