import Link from "next/link"
import { Button } from "@/components/ui/button"
import {
  Gamepad2,
  Sparkles,
  ChartBar,
  Users,
  BookOpen,
  Trophy
} from "lucide-react"

export default function Home() {
  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="container px-4 py-24 mx-auto max-w-screen-2xl">
        <div className="flex flex-col items-center text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl mb-6">
            Make English Learning{" "}
            <span className="text-primary">Fun & Engaging</span>
          </h1>
          <p className="max-w-[600px] text-lg text-muted-foreground mb-8">
            A gamified learning platform for children aged 6-12. Interactive lessons,
            AI-powered content, and personalized progress tracking.
          </p>
          <div className="flex gap-4">
            <Link href="/register">
              <Button size="lg">Start Learning Free</Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline">Log In</Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="container px-4 py-24 mx-auto max-w-screen-2xl bg-muted/50">
        <h2 className="text-3xl font-bold text-center mb-12">
          Why Kids Love Learning With Us
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <FeatureCard
            icon={<Gamepad2 className="h-8 w-8" />}
            title="Gamified Learning"
            description="Earn points, unlock achievements, and build learning streaks"
          />
          <FeatureCard
            icon={<Sparkles className="h-8 w-8" />}
            title="AI-Powered Content"
            description="Personalized stories and questions generated by AI"
          />
          <FeatureCard
            icon={<ChartBar className="h-8 w-8" />}
            title="Progress Tracking"
            description="Monitor learning progress with detailed analytics"
          />
          <FeatureCard
            icon={<Users className="h-8 w-8" />}
            title="Parent Notifications"
            description="Keep parents informed about their child's progress"
          />
        </div>
      </section>

      {/* Levels Section */}
      <section id="levels" className="container px-4 py-24 mx-auto max-w-screen-2xl">
        <h2 className="text-3xl font-bold text-center mb-4">
          4 Difficulty Levels for Every Age
        </h2>
        <p className="text-center text-muted-foreground mb-12 max-w-[600px] mx-auto">
          Content tailored to different age groups and skill levels
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <LevelCard
            level="Level 1"
            age="6-7 years"
            description="Basic vocabulary with picture cards and simple words"
            icon={<BookOpen className="h-6 w-6" />}
          />
          <LevelCard
            level="Level 2"
            age="7-8 years"
            description="Simple sentences and basic Q&A patterns"
            icon={<BookOpen className="h-6 w-6" />}
          />
          <LevelCard
            level="Level 3"
            age="8-10 years"
            description="Short paragraphs with 3-5 sentence stories"
            icon={<Trophy className="h-6 w-6" />}
          />
          <LevelCard
            level="Level 4"
            age="10-12 years"
            description="Complete stories with complex narratives"
            icon={<Trophy className="h-6 w-6" />}
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="container px-4 py-24 mx-auto max-w-screen-2xl bg-muted/50">
        <div className="flex flex-col items-center text-center">
          <h2 className="text-3xl font-bold mb-4">
            Ready to Start the Learning Journey?
          </h2>
          <p className="text-muted-foreground mb-8 max-w-[600px]">
            Join thousands of young learners exploring English through interactive stories and games
          </p>
          <div className="flex flex-col sm:flex-row gap-4 items-center">
            <Link href="/register">
              <Button size="lg">Sign Up Now</Button>
            </Link>
            <span className="text-sm text-muted-foreground">
              Already have an account?{" "}
              <Link href="/login" className="text-primary hover:underline">
                Log In
              </Link>
            </span>
          </div>
        </div>
      </section>
    </div>
  )
}

function FeatureCard({
  icon,
  title,
  description
}: {
  icon: React.ReactNode
  title: string
  description: string
}) {
  return (
    <div className="flex flex-col items-center text-center p-6 bg-card rounded-lg border">
      <div className="text-primary mb-4">{icon}</div>
      <h3 className="font-semibold mb-2">{title}</h3>
      <p className="text-sm text-muted-foreground">{description}</p>
    </div>
  )
}

function LevelCard({
  level,
  age,
  description,
  icon
}: {
  level: string
  age: string
  description: string
  icon: React.ReactNode
}) {
  return (
    <div className="flex flex-col p-6 bg-card rounded-lg border">
      <div className="flex items-center gap-2 mb-4">
        <div className="text-primary">{icon}</div>
        <div>
          <h3 className="font-semibold">{level}</h3>
          <p className="text-sm text-muted-foreground">{age}</p>
        </div>
      </div>
      <p className="text-sm text-muted-foreground">{description}</p>
    </div>
  )
}
