import Link from "next/link"
import { Button } from "@/components/ui/button"
import {
  Gamepad2,
  Sparkles,
  ChartBar,
  Users,
  BookOpen,
  Trophy
} from "lucide-react"

export default function Home() {
  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-[#ff9a9e] via-[#fecfef] to-[#fecfef] dark:from-[#2a1040] dark:via-[#1a0830] dark:to-[#1a0830] py-24">
        <div className="container flex flex-col items-center text-center px-4 mx-auto max-w-screen-2xl">
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl mb-6 text-[#311b92] dark:text-[#d4b8ff]">
            Make English Learning{" "}
            <span className="text-[#ff6b95] dark:text-[#ff8eaa]">Fun & Engaging</span>
          </h1>
          <p className="max-w-[600px] text-lg text-[#4a148c]/70 dark:text-[#c4a8e8]/60 mb-8">
            A gamified learning platform for children aged 6-12. Interactive lessons,
            AI-powered content, and personalized progress tracking.
          </p>
          <div className="flex gap-4">
            <Link href="/sms-verify">
              <Button size="lg" className="bg-gradient-to-r from-[#ff6b95] to-[#ff8e88] text-white border-0 hover:from-[#ff527b] hover:to-[#ff7a73] shadow-lg shadow-pink-200 dark:shadow-pink-900/30">
                Start Learning Free
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="bg-[#fff5f7] dark:bg-[#1e0a38] py-24">
        <div className="container px-4 mx-auto max-w-screen-2xl">
          <h2 className="text-3xl font-bold text-center mb-12 text-[#311b92] dark:text-[#d4b8ff]">
            Why Kids Love Learning With Us
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <FeatureCard
              icon={<Gamepad2 className="h-8 w-8" />}
              title="Gamified Learning"
              description="Earn points, unlock achievements, and build learning streaks"
              iconColor="text-[#0d6efd]"
              darkIconColor="dark:text-[#60a5fa]"
            />
            <FeatureCard
              icon={<Sparkles className="h-8 w-8" />}
              title="AI-Powered Content"
              description="Personalized stories and questions generated by AI"
              iconColor="text-[#6f42c1]"
              darkIconColor="dark:text-[#a78bfa]"
            />
            <FeatureCard
              icon={<ChartBar className="h-8 w-8" />}
              title="Progress Tracking"
              description="Monitor learning progress with detailed analytics"
              iconColor="text-[#198754]"
              darkIconColor="dark:text-[#4ade80]"
            />
            <FeatureCard
              icon={<Users className="h-8 w-8" />}
              title="Parent Notifications"
              description="Keep parents informed about their child's progress"
              iconColor="text-[#fd7e14]"
              darkIconColor="dark:text-[#fb923c]"
            />
            <FeatureCard
              icon={<BookOpen className="h-8 w-8" />}
              title="Interactive Stories"
              description="Engaging stories that make reading comprehension fun"
              iconColor="text-[#dc3545]"
              darkIconColor="dark:text-[#f87171]"
            />
            <FeatureCard
              icon={<Trophy className="h-8 w-8" />}
              title="Earn Rewards"
              description="Collect badges and trophies as you master new skills"
              iconColor="text-[#ffc107]"
              darkIconColor="dark:text-[#facc15]"
            />
          </div>
        </div>
      </section>

      {/* Levels Section */}
      <section id="levels" className="bg-white dark:bg-[#0f0520] py-24">
        <div className="container px-4 mx-auto max-w-screen-2xl">
          <h2 className="text-3xl font-bold text-center mb-4 text-[#311b92] dark:text-[#d4b8ff]">
            4 Difficulty Levels for Every Age
          </h2>
          <p className="text-center text-[#4a148c]/60 dark:text-[#c4a8e8]/50 mb-12 max-w-[600px] mx-auto">
            Content tailored to different age groups and skill levels
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <LevelCard
              level="Level 1"
              age="6-7 years"
              description="Basic vocabulary with picture cards and simple words"
              icon={<BookOpen className="h-6 w-6" />}
              accentColor="bg-[#0d6efd] dark:bg-[#2563eb]"
              bgColor="bg-[#e3f2fd] dark:bg-[#1e3a5f]"
            />
            <LevelCard
              level="Level 2"
              age="7-8 years"
              description="Simple sentences and basic Q&A patterns"
              icon={<BookOpen className="h-6 w-6" />}
              accentColor="bg-[#198754] dark:bg-[#16a34a]"
              bgColor="bg-[#e8f5e9] dark:bg-[#1a3a1e]"
            />
            <LevelCard
              level="Level 3"
              age="8-10 years"
              description="Short paragraphs with 3-5 sentence stories"
              icon={<Trophy className="h-6 w-6" />}
              accentColor="bg-[#fd7e14] dark:bg-[#ea580c]"
              bgColor="bg-[#fff3e0] dark:bg-[#3a2510]"
            />
            <LevelCard
              level="Level 4"
              age="10-12 years"
              description="Complete stories with complex narratives"
              icon={<Trophy className="h-6 w-6" />}
              accentColor="bg-[#6f42c1] dark:bg-[#7c3aed]"
              bgColor="bg-[#f3e5f5] dark:bg-[#2a1a3a]"
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-br from-[#ff9a9e] via-[#fecfef] to-[#fecfef] dark:from-[#2a1040] dark:via-[#1a0830] dark:to-[#1a0830] py-24">
        <div className="container flex flex-col items-center text-center px-4 mx-auto max-w-screen-2xl">
          <h2 className="text-3xl font-bold mb-4 text-[#311b92] dark:text-[#d4b8ff]">
            Ready to Start the Learning Journey?
          </h2>
          <p className="text-[#4a148c]/60 dark:text-[#c4a8e8]/50 mb-8 max-w-[600px]">
            Join thousands of young learners exploring English through interactive stories and games
          </p>
          <div className="flex flex-col sm:flex-row gap-4 items-center">
            <Link href="/sms-verify">
              <Button size="lg" className="bg-gradient-to-r from-[#ff6b95] to-[#ff8e88] text-white border-0 hover:from-[#ff527b] hover:to-[#ff7a73] shadow-lg shadow-pink-200 dark:shadow-pink-900/30">
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}

function FeatureCard({
  icon,
  title,
  description,
  iconColor,
  darkIconColor
}: {
  icon: React.ReactNode
  title: string
  description: string
  iconColor: string
  darkIconColor: string
}) {
  return (
    <div className="flex flex-col items-center text-center p-6 bg-white dark:bg-[#22103a] rounded-2xl border border-pink-50 dark:border-[#3a1a5a] shadow-sm hover:-translate-y-1 hover:shadow-lg transition-all">
      <div className={`${iconColor} ${darkIconColor} mb-4`}>{icon}</div>
      <h3 className="font-semibold mb-2 text-[#311b92] dark:text-[#d4b8ff]">{title}</h3>
      <p className="text-sm text-[#4a148c]/50 dark:text-[#c4a8e8]/40">{description}</p>
    </div>
  )
}

function LevelCard({
  level,
  age,
  description,
  icon,
  accentColor,
  bgColor
}: {
  level: string
  age: string
  description: string
  icon: React.ReactNode
  accentColor: string
  bgColor: string
}) {
  return (
    <div className={`flex flex-col p-6 ${bgColor} rounded-2xl border border-white/50 dark:border-white/10 hover:-translate-y-1 hover:shadow-lg transition-all`}>
      <div className="flex items-center gap-3 mb-4">
        <div className={`${accentColor} text-white p-2 rounded-lg`}>{icon}</div>
        <div>
          <h3 className="font-semibold text-[#311b92] dark:text-[#d4b8ff]">{level}</h3>
          <p className="text-sm text-[#4a148c]/50 dark:text-[#c4a8e8]/40">{age}</p>
        </div>
      </div>
      <p className="text-sm text-[#4a148c]/60 dark:text-[#c4a8e8]/40">{description}</p>
    </div>
  )
}
